### ISSUE TITLE
What does the Ubuntu icon mean in ukuu?

### ISSUE THREAD

**Issue by laichiaheng** [teejee2008/ukuu#109]
**Describe the bug**
There is an Ubuntu icon

**To Reproduce**
1. Go to 'application'
2. Click on 'ukuu'
3. An Ubuntu icon in it.

**Expected behavior**
Nothing.

**Screenshots**
![2018-10-23 08-35-26](https://user-images.githubusercontent.com/9532105/47327210-e8942580-d69e-11e8-9d52-cc2d063341b7.png)

**System (please complete the following information):**
 - Linux Distribution Name and Version: [Ubuntu 18.04]
 - Desktop [Gnome3]
 - Application Version [v18.9]

***Consider making a donation to support this project***

[![](https://www.paypalobjects.com/en_US/i/btn/btn_donate_LG.gif)](https://www.paypal.com/cgi-bin/webscr?business=teejeetech@gmail.com&cmd=_xclick&currency_code=USD&item_name=Ukuu%20Donation)

**Comment by yolateng0** [comment]
It s a official ubuntu kernel.
