### ISSUE TITLE
UKUU does not install linux-tools for the kernel

### ISSUE THREAD

**Issue by elbow** [teejee2008/ukuu#12]
Hi,

I notice that UKUU does not install linux-tools(-common) for the installed kernel.

I came across this after updating to 4.10.10 on my Elementary Loki machine.  Under the new kernel tlp-stat complains:

>>   x86_energy_perf_policy: program for your kernel not installed.

I guess this isn't critical but on a modern laptop I understand that this does effect power consumption.  "cpupower" also complains that the packages are missing for the running kernel.

Thanks,
Steve

**Comment by teejee2008** [comment]
Canonical does not provide the package _linux-tools-common_ on [kernel.ubuntu.com](url). Stick to the official kernels if you need the additional packages.
