### ISSUE TITLE
Can't install Linux 4.20.1 : not listed

### ISSUE THREAD

**Issue by Huluti** [teejee2008/ukuu#122]
The latest 4.20.1 is not listed in the list of available kernels while it is in [Ubuntu Mainline](https://kernel.ubuntu.com/~kernel-ppa/mainline/v4.20.1/).

![image](https://user-images.githubusercontent.com/5782198/50991854-f1fe9280-1515-11e9-848f-a781bb51d8d2.png)

 - Ubuntu 18.10
 - GNOME
 - v18.5.1

**Comment by gothicVI** [comment]
Are you running a 64bit CPU? If so take a look at your link.

**Comment by Huluti** [comment]
Oops... sorry not to have been curious ...

**Comment by antonio-petricca** [comment]
Why this thread has been closed? The issue is still present.

**Comment by gothicVI** [comment]
@antonio-petricca because it is NOT a ukuu issue.

**Comment by gothicVI** [comment]
Once again @antonio-petricca THIS IS NOT A UKUU ISSUE! The kernel build failed on Ubuntu's side so you could have tried to resolve that on launchpad but not here.

**Comment by antonio-petricca** [comment]
Once again: I understood what you said, but I think it is the right thing to inform UKUU users that now they can use it with 4.20 too. Regards.
