### ISSUE TITLE
4.20.1 is not in the list.

### ISSUE THREAD

**Issue by laichiaheng** [teejee2008/ukuu#123]
**Describe the bug**
I can't find 4.20.1

**To Reproduce**
1. Go to 'ukuu'

**Expected behavior**
4.20.1 appears.

**System (please complete the following information):**
 - Linux Distribution Name and Version: [e.g. Ubuntu 18.10]
 - Desktop [e.g. GNOME3]
 - Application Version [e.g. ?]

**Comment by laichiaheng** [comment]
I need to remove all the files in my .cache/ukuu/

**Comment by gothicVI** [comment]
https://github.com/teejee2008/ukuu/issues/122

**Comment by laichiaheng** [comment]
My bad
