### ISSUE TITLE
Ukuu does not install 4.20.2

### ISSUE THREAD

**Issue by antonio-petricca** [teejee2008/ukuu#126]
I am on Linux Mint 19.1 Mate 64 bit. I am running 4.20, and I want to upgrade to 4.20.2.

UKUU does not show the 4.20.2, so I did the following steps:

1. Opened the terminal.
2. Run `ukuu --clean--cache`.
3. Run `ukuu --list | grep v4.20` and now I see then 4.20.2.
4. Run `ukuu --install v4.20.2`.
5. UKUU downloads the new kernel.
6. UKUU tries to install it.
7. UKUU says that the installation was successfully completed.
8. UKUU runs `update-grub`.
9. The new kernel is not present!

Thank you!

**Comment by gothicVI** [comment]
Please read through existing issues and with this one also take a look at the closed ones.

**Comment by antonio-petricca** [comment]
Closed because it duplicates #122 .
