### ISSUE TITLE
Changes not displayed

### ISSUE THREAD

**Issue by sphh** [teejee2008/ukuu#16]
When pressing the `Changes` button with a kernel release (the newest) selected, nothing happens.

`ukuu-gtk --debug` does not show any error message.

**Comment by sphh** [comment]
I looked through the source code and found that `exo_open_textfile` uses either `exo-open` or `gedit` to display the file. Both are not available on my system (Linux Mint 18.2). Would it be possible to use a more generic way to display the file? I was thinking in the line of using the editor set in "Preferred Application" in Ubuntu (and Linux Mint)... Thanks.

**Comment by teejee2008** [comment]
Fixed in v17.12
