### ISSUE TITLE
Remove dependency on X and GTK for command line version

### ISSUE THREAD

**Issue by teejee2008** [teejee2008/ukuu#18]
The command line version can currently be used only if a display is available. Remove dependency on X and GTK.

**Comment by Mosi2772** [comment]
This is useful software Thanks!

**Comment by numericOverflow** [comment]
Agreed, I'd like to use from my headless server, but can't because there's no X running, even though I want to run the command line version and not the GTK GUI.

```
root@server:~# ukuu --help
Failed to connect to Mir: Failed to connect to server socket: No such file or directory
Unable to init server: Could not connect: Connection refused

(ukuu:8965): Gtk-WARNING **: cannot open display:

```

**Comment by teejee2008** [comment]
Added in v17.12.1
