### ISSUE TITLE
ukuu shows no internet connection

### ISSUE THREAD

**Issue by siddht4** [teejee2008/ukuu#19]
ukuu always shows no internet connection dialog box but can get all the new kernels.When installing the same no internet connection error occurs

**Comment by krbaio3** [comment]
I have same problem

**Comment by jerdog** [comment]
Is this the error message you're receiving @krbaio3 / @siddht4 ?

![image](https://user-images.githubusercontent.com/296864/31185704-448a087c-a8f2-11e7-8ff9-6db7f5a16c63.png)

**Comment by siddht4** [comment]
Closing this issue as https://github.com/teejee2008/ukuu/pull/24/commits/219ca76f413d4e4c490c8ade5170fde1cb268989  fixed it.

**Comment by Bavarianph** [comment]
make (in directory: /home/ibp/Downloads/ukuu-master)
cd src; make all
make[1]: Entering directory '/home/ibp/Downloads/ukuu-master/src'
#build binaries
#app-gtk
valac -X -D'GETTEXT_PACKAGE="ukuu"' --Xcc="-lm" -X -Wl,-rpath,/usr/share/ukuu/libs -D VTE_291 --thread Common/*.vala Gtk/*.vala Utility/*.vala Utility/Gtk/*.vala -o ukuu-gtk --pkg glib-2.0 --pkg gio-unix-2.0 --pkg posix --pkg gtk+-3.0 --pkg gee-0.8 --pkg json-glib-1.0 --pkg vte-2.91
Compilation failed: 2 error(s), 0 warning(s)
makefile:16: recipe for target 'all' failed
make[1]: Leaving directory '/home/ibp/Downloads/ukuu-master/src'
makefile:2: recipe for target 'all' failed
error: Package `gee-0.8' not found in specified Vala API directories or GObject-Introspection GIR directories
error: Package `vte-2.91' not found in specified Vala API directories or GObject-Introspection GIR directories
make[1]: *** [all] Error 1
make: *** [all] Error 2
Compilation failed.
I am unable to meet the 2 dependencies. 
Why can't you just make a deb file.
Without a curl ukuu deb file this program is useless.
I am not a programmer and your #19 fix is uncompilable for me!

**Comment by siddht4** [comment]
@Bavarianph  did you upgrade ukuu or not

**Comment by Bavarianph** [comment]
I have ukuu version 17.12-0~201712091333 Ubuntu 17.10.1 (artful) using your ppa
and it gives me the "no Internet" message when ukuu starts and again when I chose to install.
It does not install anything! Yet I install 100's of other repos and files with no problem.
Ubuntu updater also has no problem installing new updates.

**Comment by siddht4** [comment]
re-opening the issue as @Bavarianph  is still having the issue

**Comment by Bavarianph** [comment]
ukuu-5be9a9aa1852d3c3889a84fed618d4ebbe94f6ff
compiled successfully
installed & now works very well
checkinstall was able to create a ukuu deb file.

Thank you very much.
New kernel installed and working fine.

BavarianPH

**Comment by siddht4** [comment]
@Bavarianph is your ukuu working properly? if yes then I will agin close the issue

**Comment by Bavarianph** [comment]
My reply meant to say that everything was now working.
So, yes, ukuu works very well now.
Thank you very much.
BavarianPH

**Comment by kartun83** [comment]
I'm on mint 18.3, and ukuu 18.1
I have same issue.

> ukuu --check
> ukuu v18.1
> Distribution: Linux Mint 18.3 Sylvia
> Architecture: amd64
> Running kernel: 4.14.11-041411-generic
> Kernel version: 4.14.11-041411-generic
> Cache: /home/kartun/.cache/ukuu
> Temp: /tmp/ukuu/dl0EsrbI
> E: Internet connection is not active
> E: Internet connection is not active
> ----------------------------------------------------------------------
> Found installed: 4.14.11-041411.201801022143
> Found installed: 4.14.8-041408.201712200555
> Found installed: 4.14.9-041409.201712251541
> Found installed: 4.10.0-38.42~16.04.1
> Found installed: 4.14.10-041410.201712291810
> ----------------------------------------------------------------------
> Latest point update: 4.14.14
> ----------------------------------------------------------------------

and
ukuu --install-latest
ukuu v18.1
Distribution: Linux Mint 18.3 Sylvia
Architecture: amd64
Running kernel: 4.14.11-041411-generic
Kernel version: 4.14.11-041411-generic
Cache: /home/kartun/.cache/ukuu
Temp: /tmp/ukuu/WbeIWOP9
E: Internet connection is not active

**Comment by ephillipe** [comment]
@cdplayer,  I'm too with the same problem.

```
$ sudo ukuu --check
ukuu v18.5.1
Distribution: Ubuntu 18.04 LTS
Architecture: amd64
Running kernel: 4.15.0-22-generic
Kernel version: 4.15.0.22.24
Cache: /.cache/ukuu
Temp: /tmp/ukuu/QY8TFkk6
E: Internet connection is not active
E: Internet connection is not active
----------------------------------------------------------------------
Found installed: 4.15.0.22.23
Found installed: 4.15.0-22.24
Found installed: 4.15.0-20.21
----------------------------------------------------------------------
Latest update: 4.16.11
Latest point update: 4.15.18
----------------------------------------------------------------------

```

**Comment by l2009312042** [comment]
E: Internet connection is not active
same error  anyone solve it ？
