### ISSUE TITLE
Ukuu Doesn't Provide A Kernel Type Setting

### ISSUE THREAD

**Issue by voice06** [teejee2008/ukuu#2]
More of a feature request than a bug.

As the title says, at the present time Ukuu doesn't provide a list of kernel types to chose from via settings, instead it is hard-coded to use -generic which is fine for most people. That said, it would be nice to be able to tell Ukuu I want the -lowlatency kernel instead of the -generic kernel.

**Comment by teejee2008** [comment]
Duplicate of #5
