### ISSUE TITLE
On 17.10 attempt to install 4.13.4 kernel results in error

### ISSUE THREAD

**Issue by jerdog** [teejee2008/ukuu#25]
Using the CLI the following error is received:
```
$ sudo ukuu --install 4.13.4
[sudo] password for : 
Invalid MIT-MAGIC-COOKIE-1 keyUnable to init server: Could not connect: Connection refused

(ukuu:7669): Gtk-WARNING **: cannot open display: :0
```

**Comment by rosterloh** [comment]
Same here for 4.13.6. Must be a Wayland issue

**Comment by fuelflo** [comment]
possible related to: #13 
have the same problem using ukuu on wayland.

**Comment by jignesh248** [comment]
same issues after updating ubuntu to 17.10 i.e. wayland

**Comment by kseyhan** [comment]
check my proposed solution at [#13](https://github.com/teejee2008/ukuu/issues/13)

**Comment by jgoodleaf** [comment]
@kseyhan 's solution works, though you probably shouldn't leave `xhost +` enabled.

**Comment by fgblomqvist** [comment]
I am running Ubuntu 17.10, but using the Xorg session, and can successfully install kernels. As in, this must be a Wayland issue.

**Comment by kseyhan** [comment]
yes thats right @jgoodleaf use 

`xhost -`

after youre finished.

**Comment by craigcarnell** [comment]
Any idea when wayland will be supported?

**Comment by teejee2008** [comment]
Duplicate of #9
