### ISSUE TITLE
Locale problem when reading the kernel changes

### ISSUE THREAD

**Issue by CottonEaster** [teejee2008/ukuu#29]
Thank you for the latest update, and more generally for this tremendously useful piece of software.

On version 17.12 of ukuu, as indeed on previous versions, my text editor - Sublime Text 3 - gives an error when (via ukuu's useful 'changes' buttun) it (Sublime) opens the changelog. See screenshot.

![image](https://user-images.githubusercontent.com/9998846/33801951-7ab6e9b0-dd63-11e7-9cca-25e68f98a050.png)

Sublime does not normally show this message on my system. I think the cause might be a bash script setting the character 'encoding' (for I did once make similar problems myself with a script).

**Comment by teejee2008** [comment]
The Changes file can have Non-ASCII characters (non-english). Sublime is warning you that your locale does not handle Non-ASCII characters. You may need to update your locale settings, or settings in Sublime.

**Comment by CottonEaster** [comment]
You may well be right; there's a fair amount of stuff on the web about Sublime and locale problems. However, the following may be notable. I copied `ukuu`'s cached file and opened it, from a terminal, without any problems or warnings, in both (1) `xed`, (2) Sublime; it's only when the file is opened via `ukuu` that I receive the warning.

**Comment by CottonEaster** [comment]
The following fixed it for me, on Mint Cinnamon, and for a system language of British English.

Put the following in /etc/locale.conf, creating the file if necessary:

```
LANG=en_GB.UTF-8
LC_CTYPE=en_GB.UTF-8
```
