### ISSUE TITLE
Ukuu notifies for an update even though a newer kernel is already installed

### ISSUE THREAD

**Issue by shrx** [teejee2008/ukuu#3]
I am running kernel v4.10.6, and have kernel v4.10.8 installed. Despite this, Ukuu still notifies me that there is an update, v4.10.7, to be installed.
I believe this shouldn't happen as I already have a newer kernel verison installed. Is it a bug?

**Comment by teejee2008** [comment]
Turn off the notification from Settings window. Will be fixed in next update.

**Comment by teejee2008** [comment]
Fixed in v17.12
