### ISSUE TITLE
Not finding Kernel v4.15 on Ubuntu 16.04

### ISSUE THREAD

**Issue by atomiczap** [teejee2008/ukuu#46]
A few days ago (before the new update) I was able to use ukuu to update my kernel to version 4.15-rc7.  I have since had to reinstall Ubuntu so I tried to update my kernel again and the newest version ukuu shows when running --list is 4.14.13.  I have checked on a second computer and get the same result.  Is there a way to install the previous version of ukuu (before the update 2 days ago) so I can see if that still works?

**Comment by eson57** [comment]
Did you uncheck "Settings/Hide unstable and RC releases"?

**Comment by atomiczap** [comment]
I did not, I'd only been using ukuu through the terminal and didn't realize there was a gui with options like that.  Thanks!
