### ISSUE TITLE
Home directory is not detected correctly

### ISSUE THREAD

**Issue by teejee2008** [teejee2008/ukuu#6]
ukuu using wrong cache directory
Using cache directory: /home/a.kozhevnikov/.cache/ukuu
But my home is /home/OMP/a.kozhevnikov
-- CODeRUS

**Comment by CODeRUS** [comment]
Thanks, i failed at searching repo with source code myself :D

**Comment by MurzNN** [comment]
Got the same problem - I have homedir at /home/COMPANYNAME/korepov but ukuu tries to save into /home/korepov/.cache/ukuu

**Comment by teejee2008** [comment]
Fixed in v17.12
