### ISSUE TITLE
the debian download is offline

### ISSUE THREAD

**Issue by rubo77** [teejee2008/ukuu#60]
At the UKUU download page the downloads are all offline: http://www.teejeetech.in/p/ukuu-kernel-upgrade-utility.html

seems like the dropbox wasn't such a good place to serve the sownloads ;)

Could you fix the download links please? I would like to install ukuu on Debian.

**Comment by rubo77** [comment]
Or if debain is not supported as mentioned in the current Readme here https://github.com/teejee2008/ukuu#debian--other-linux-distributions, then please remove the links from the download page.

But I think it would be easy for you to adapt the tool so it uses the latest Debian kernels then from Debians **experimentals**, wouldn't it?

**Comment by teejee2008** [comment]
https://github.com/teejee2008/ukuu/releases

**Comment by teejee2008** [comment]
I'm not sure if it will cause problems on Debian. Try it and let me know.
