### ISSUE TITLE
ukuu-uninstall?

### ISSUE THREAD

**Issue by edmundlaugasson** [teejee2008/ukuu#67]
For what purpose is _ukuu-uninstall_? It will disable ukuu command but package is still installed. No help is available, even _ukuu-uninstall --help_ will disable ukuu command. Also no man page is available. Also main program help (_ukuu --help_) does not mention it.

**Comment by teejee2008** [comment]
If you installed ukuu using the Installer then the ukuu-uninstall script will remove it from the system. If you installed using package manager then it is not required.

**Comment by edmundlaugasson** [comment]
it would be worth to have a description in help about that point
