### ISSUE TITLE
Error when installing 4.16.4

### ISSUE THREAD

**Issue by v1993** [teejee2008/ukuu#69]
I tried to install fresh 4.16.4 kernel and got error about missing package `linux-modules-...`, so `linux-image-unsigned-...` (or something like that) can't be configured.

Did kernel packaging structure changed?

**Comment by gothicVI** [comment]
If you compare the builds for 4.16.2 or 4.16.3 [1] with 4.16.4 [2] you realize that with the .4 release no images were built but only unsigned images. I don't know why but eventually there's something wrong with the built chain - although the build finished successfully.

[1] [http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.16.3/](4.16.3)
[2] [http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.16.4/](4.16.4)

**Comment by teejee2008** [comment]
This will be fixed in the next update.

**Comment by SamMorrowDrums** [comment]
Hey - I've posted in another issue, related to this but for those who don't want to wait, they have actually changed the way they are distributing the mainline kernel so almost all advice on the internet is slightly wrong at the moment!

For Ubuntu users, you can do this:

Firstly, to install properly you need the upcoming, but not released linux-base_4.5ubuntu1~16.04.1_all.deb from https://launchpad.net/ubuntu/+source/linux-base

You then need to also install the correct modules from here: http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.16.5/

Most likely you need:

linux-headers-4.16.5-041605_4.16.5-041605.201804260630_all.deb
linux-headers-4.16.5-041605-generic_4.16.5-041605.201804260630_amd64.deb
linux-modules-4.16.5-041605-generic_4.16.5-041605.201804260630_amd64.deb
and maybe also
linux-image-unsigned-4.16.5-041605-generic_4.16.5-041605.201804260630_amd64.deb

Finally `sudo dpkg -i ` all those .deb files.

For more context on this bug (from a Ubuntu standpoint)

https://bugs.launchpad.net/ubuntu/+source/linux-base/+bug/1766851

After doing the above I have install success. Ukuu will need to be patched to handle the new kernels!

@teejee2008 - do you have a solution that doesn't rely on Ubuntu pushing the update to linux-base package to work?

**Comment by SamMorrowDrums** [comment]
Obviously, with the above, I have gave instructions for 4.16.5 - but you might want still want .4 for some reason, so as always with manual kernel installation - don't blindly follow the instructions!

**Comment by teejee2008** [comment]
Once Ubuntu releases a new version of linux-base, Ukuu can download and install it along with the rest of the kernel packages. We need to wait till the next release of linux-base.

**Comment by dc740** [comment]
I'm on Ubuntu 18.04LTS, with the latest linux-base, and I can confirm I still need to manually download the modules deb to get the kernel working. I'm on 4.17rc3 now.

**Comment by peci1** [comment]
Ukuu 18.5.1 solved this issue for me.

I'm (still) on Trusty, ukuu compiled from source, libssl1.1 was already installed by some other program. Kernel 4.16.11 installed without a problem.

**Comment by v1993** [comment]
It is fixed for me, so I close this issue.
