### ISSUE TITLE
wayland + UKUU

### ISSUE THREAD

**Issue by okias** [teejee2008/ukuu#9]
Using ubuntu 16.04 based KDE Neon with Wayland and getting error:

```
No protocol specified
Failed to connect to Mir: Failed to connect to server socket: No such file or directory
Unable to init server: Could not connect: Connection refused

(ukuu:6000): Gtk-WARNING **: cannot open display: :1 

Close window to exit
```

Since MIR is dead, feel free to prepare UKUU to support Wayland :) it's move in right way.

Thank you

**Comment by Vistaus** [comment]
I'm pretty sure that that's a GTK error and not a Ukuu error and you don't seem to be running Wayland as GTK is complaining about Mir...

**Comment by okias** [comment]
Trick is, that KDE Plasma is able to run only on X11 or Wayland.

Anyway, it could be GTK bug, if you're sure app is not hardcoded to X11 or Mir.

**Comment by jvalenciag** [comment]
This is because ukuu is not compliant of the new security of wayland as explained [here](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=818366)

running  `xhost +si:localuser:root` before starting ukuu worked for me.

**Comment by jerdog** [comment]
Also receiving this error on 17.10

![image](https://user-images.githubusercontent.com/296864/31185704-448a087c-a8f2-11e7-8ff9-6db7f5a16c63.png)

**Comment by Hasimir0** [comment]
Is this command permanent?
Or will it be erased after a system reboot?
If so, is there a way to save it somehow?

**Comment by craigcarnell** [comment]
Please add Wayland support :+1:

**Comment by teejee2008** [comment]
Added in v17.12.1
